version: '3'

services:

  consul:
    image: consul:1.6
    container_name: consul
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500
        
  service:
    image: service
    container_name: service
    restart: on-failure
    build:
      context: ./Service
      dockerfile: Dockerfile
    ports:
      - 6001:80
    environment:
      CONSUL_HOST: http://consul:8500
    depends_on:
      - consul
      - employee
      - role
      - department

  employee:
    image: employee
    container_name: employee
    restart: on-failure
    build:
      context: ./Employee
      dockerfile: Dockerfile
    ports:
      - 6003:80
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: EmployeeAdmin
      DATABASE_USER: sa
      DATABASE_PASSWORD: P@55w0rd
      CONSUL_HOST: http://consul:8500
      SERVICE_PORT: 80
    depends_on:
      - consul
      - database

  role:
    image: role
    container_name: role
    restart: on-failure
    build:
      context: ./Role
      dockerfile: Dockerfile
    ports:
      - 6005:80
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: EmployeeAdmin
      DATABASE_USER: sa
      DATABASE_PASSWORD: P@55w0rd
      CONSUL_HOST: http://consul:8500
      SERVICE_PORT: 80
    depends_on:
      - consul
      - database

  department:
    image: department
    container_name: department
    restart: on-failure
    build:
      context: ./Department
      dockerfile: Dockerfile
    ports:
      - 6007:80
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: EmployeeAdmin
      DATABASE_USER: sa
      DATABASE_PASSWORD: P@55w0rd
      CONSUL_HOST: http://consul:8500
      SERVICE_PORT: 80
    depends_on:
      - consul
      - database

  database:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: database
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
    environment:
      SA_PASSWORD: P@55w0rd
      ACCEPT_EULA: "Y"

  database-schema:
    image: mcr.microsoft.com/mssql-tools
    container_name: database-schema
    volumes:
      - ./assets:/service
    working_dir: /service
    command: bash -c "chmod +x entry-point.sh && ./entry-point.sh"
    environment:
      SA_HOST: database
      SA_PASSWORD: P@55w0rd
    depends_on:
      - database